# Generated by Django 6.0.3 on 2026-06-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='logo/')),
                ('favicon', models.ImageField(upload_to='favicon/')),
                ('nav_links', models.JSONField(default=list)),
                ('footer_text', models.TextField(blank=True)),
                ('footer_links', models.JSONField(default=list)),
            ],
        ),
    ]
