# Generated by Django 6.0.3 on 2026-06-23 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_links',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='footer_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='nav_links',
        ),
    ]
