# Generated by Django 6.0.3 on 2026-06-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pageview_visitorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='logo',
            new_name='logo_dark',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_light',
            field=models.ImageField(default='1', upload_to='logo/'),
            preserve_default=False,
        ),
    ]
