# Generated by Django 6.0.3 on 2026-06-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_logo_sitesettings_logo_dark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_image', models.ImageField(upload_to='footer/')),
                ('footer_email', models.CharField(max_length=254)),
                ('footer_phone', models.CharField(max_length=13)),
            ],
        ),
    ]
