# Generated by Django 6.0.3 on 2026-06-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_rights',
            field=models.CharField(default='© 2023 OLIVIA. All rights reserved', max_length=254),
            preserve_default=False,
        ),
    ]
