# Generated by Django 6.0.3 on 2026-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_footer_footer_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='footer_links',
            field=models.JSONField(default=list),
        ),
    ]
