# Generated by Django 6.0.3 on 2026-06-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cta_1', models.CharField(max_length=100)),
                ('cta_2', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='home/')),
            ],
        ),
    ]
